name: Build & Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'Dockerfile'

jobs:
  be:
    name: 💻 Build & deploy server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aspenjames/aspenjames.dev:latest

    - name: Auth w/ Google
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}

    - name: Restart server daemon
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: 'dot-dev-server'
        zone: 'us-west1-b'
        ssh_private_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
        command: 'sudo systemctl restart dot_dev.service'
