name: Build & Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'Dockerfile'

jobs:
  be:
    name: 💻 Build & deploy server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aspenjames/aspenjames.dev:latest

    - name: Setup ssh keyfile
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dot_dev
        chmod 0600 ~/.ssh/dot_dev

    - name: Restart server daemon
      run: |
        ssh -i ~/.ssh/dot_dev \
          "root@${{ secrets.LINODE_IP }}" \
          systemctl restart dot_dev
